config/routes.rb
MiniBlog::Application.routes.draw do
  get "sessions/new"

  get 'sign-up', to: 'authors#new', as: :signup
  get 'sign-in', to: 'sessions#new', as: :signin
  delete 'sign-out', to: 'sessions#destroy', as: :signout

  resources :authors
  resources :sessions
  resources :posts 
  resources :comments

  root to: 'home#index'
  

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_secure_password
  has_many :posts
  has_many :comments, through: :posts
  attr_accessible :bio, :email, :first_name, :last_name, :twitter, :username, :password, :password_confirmation
  #presence
  validates :password, :password_confirmation, presence: true, on: :create
  validates :email, :first_name, :last_name, :username, presence: true
  #uniqueness
  validates :email, :username, :twitter, uniqueness: true, allow_blank: true
  #length
  validates :password, :password_confirmation, length: {in: 6..24}
  #validates :email, presence: true,
   #                 uniqueness: true,
   #                 length: { minimum: 3}
   def full_name
    (first_name + ' ' + last_name).titleize
   end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :commenter_name, :message, :post_id
  validates :commenter_name, :message, :post, presence: true
  validates :message, length: { minimum: 30 }
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author
  has_many :comments, dependent: :destroy
  attr_accessible :body, :published_at, :title, :author_id
  validates :author, presence: {message: "must actually exist."}
  validates  :body, :title, presence: true
  validates :body, length: { minimum: 50 }
  validates :title, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_author
    @current_author ||= Author.find(session[:author_id]) if session[:author_id]
  end
  helper_method :current_author

  def authorize
    redirect_to root_url, alert: "Not Logged In" if current_author
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created, location: @author }
      else
        format.html { render action: "new" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    redirect_to post_path(@post)

    
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authorize, except: [:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.where("published_at <= ?", Time.now).order("published_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = current_author.posts.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_author.posts.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    author = Author.find_by_email(params[:email])
    if author && author.authenticate(params[:password])
      session[:author_id] = author.id
      redirect_to root_url, notice: "Signed In!"
    else
      flash.now.alert = "Email or password is invalid"
      render :new
    end
  end

  def destroy
    session[:author_id] = nil
    redirect_to root_url, notice: "Signed out"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/authors/_form.html.erb
<%= simple_form_for @author do |f| %>
  <%= f.error_notification %>
  <%= f.input :first_name, placeholder: "Enter your first name" %>
  <%= f.input :last_name %>
  <%= f.input :username %>
  <%= f.input :bio, input_html: {rows: 3}, placeholder: "Write something about yourself." %>
  <%= f.input :email %>
  <%= f.input :twitter %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.button :submit %>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Username</th>
    <th>Bio</th>
    <th>Email</th>
    <th>Twitter</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authors.each do |author| %>
  <tr>
    <td><%= author.first_name %></td>
    <td><%= author.last_name %></td>
    <td><%= author.username %></td>
    <td><%= author.bio %></td>
    <td><%= author.email %></td>
    <td><%= author.twitter %></td>
    <td><%= link_to 'Show', author %></td>
    <td><%= link_to 'Edit', edit_author_path(author) %></td>
    <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
<%= @author.full_name %>
</h1>

<p>
  <b>Username:</b>
  <%= @author.username %> | <%= mail_to @author.email %>
</p>

<p>
  <b>Bio:</b>
  <%= @author.bio %>
</p>

<p>
  <b>Twitter:</b>
  <%= @author.twitter %>
</p>
<hr />
<h3> <%= @author.username%>'s posts<h3/>
<% @author.posts.each do |post| %>
  <h2><%= link_to post.title.titleize, post%></h2>
  <h4><%= time_tag(post.published_at.to_date) %></h4>
  <p><%= simple_format(post.body) %></p>
<% end %>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :commenter_name %><br />
    <%= f.text_field :commenter_name %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br />
    <%= f.text_field :post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Commenter name</th>
    <th>Message</th>
    <th>Post</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.commenter_name %></td>
    <td><%= comment.message %></td>
    <td><%= comment.post %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Commenter name:</b>
  <%= @comment.commenter_name %>
</p>

<p>
  <b>Message:</b>
  <%= @comment.message %>
</p>

<p>
  <b>Post:</b>
  <%= @comment.post %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/home/index.html.erb
<h1>Chris's Dope Blog</h1>
<p>Chris is the coolest ruby on rails programmer ever. * infinity</p>
<p>It is now <%= time_tag(Time.now) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MiniBlog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/navigation' %>
<% flash.each do |name, msg| %>
  <%=content_tag :div, msg, id: "flash_#{name}" %>
<% end %>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>
  <%= f.input :title %>
  <%= f.input :body %>
  <%# f.association :author, collection: Author.all.collect {|p| [p.username, p.id]} %>
  <%= f.input :published_at %>
  <%= f.button :submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts(<%= @posts.count %>)</h1>



<% @posts.each do |post| %>
  <h2><%= post.title.titleize %></h2>
  <h4><%= link_to(post.author.try(:username), author_path(post.author)) if post.author%> | <%= time_tag(post.published_at.to_date) %></h4>
  <p><%= simple_format(truncate(post.body, length: 140, separator: ' ')+ link_to("Continue Reading", post)) %></p>
  
  <%= link_to 'Show', post %>
  <%= link_to 'Edit', edit_post_path(post) %>
  
<% end %>

<%= link_to 'New Post', new_post_path if current_author %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

  <h2><%= @post.title.titleize %></h2>
  <h4><%= link_to(@post.author.try(:username), author_path(@post.author))%><%= time_tag(@post.published_at.to_date) %></h4>
  <p><%= @post.body.html_safe %></p>

<h3>Comments</h3>
<% @post.comments.each do |comment| %>
 
    <p><b><%= comment.commenter_name %></b><p>
    <p><%= comment.message %></p>

  
<% end %>

<%= form_for @comment do |f| %>

  <div class="field">
    <%= f.label :commenter_name %><br />
    <%= f.text_field :commenter_name %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/shared/_navigation.html.erb
<nav id='primary-navigation'>
  <ul>
    <li>
      <%= link_to "Home", root_path, class: "home-link" %>
    </li>
    <li>
      <%= link_to "My_Blog", posts_path %>
    </li>
    <li>
      <%= link_to "All_Authors", authors_path %>
    </li>
    <div class='pull-right'>
      <% if current_author %>
      <li>
        Logged in as <%= link_to current_author.username, author_path(current_author) %>
        |
        <%= link_to "Sign Out!", signout_path, method: :delete %>
      </li>
      <% else %>
      <li>
        <%= link_to 'Sign Up', signup_path %>
      </li>
      <li>
        <%= link_to 'Sign In', signin_path %>
      </li>
      <% end %>
    </li>
    </div>
  </ul>
</nav>